version: "3"
services:
  unbound:
    image: "mvance/unbound:1.17.0"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./unbound:/opt/unbound/etc/unbound/"
    networks:
      private_network:
        ipv4_address: 10.2.0.200

  wg_dashboard:
    #image: noxcis/wg-dashboard:latest
    image: donaldzou/wgdashboard:v3.1-dev
    depends_on: [unbound, adguardhome]
    container_name: dwg-dash
    restart: unless-stopped 
    cap_add: 
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TZ=Europe/Moscow
      - SERVER_IP=MYHOST_IP
      - CONFIG_CT=1      
    volumes:
      - ./wgdash:/etc/wireguard
    ports:
      - 10086:10086
      - 51820:51820/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 10.2.0.100
    networks:
      private_network:
        ipv4_address: 10.2.0.3

  adguardhome:
    depends_on: [unbound]
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    networks:
      private_network:
        ipv4_address: 10.2.0.100

networks:
  private_network:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
